[package]
name = "osdbuf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
# crate-type = ["staticlib"]

[dependencies]
# ab_glyph = "0.2"
fontdue = "0.9.3"
once_cell = "1.18"
parking_lot = "0.12"
tiny-skia = "0.12.0"
