[target.mipsel-unknown-linux-gnu]
linker = "/home/murphy/pyproj/pytoui/mips32el--glibc--stable-2018.11-1/bin/mipsel-linux-gcc"
ar = "/home/murphy/pyproj/pytoui/mips32el--glibc--stable-2018.11-1/bin/mipsel-linux-ar"

rustflags = [
    "-C", "link-arg=-lc",
    "-C", "link-arg=-lm",
]

[target.mipsel-unknown-linux-musl]
linker = "/home/murphy/pyproj/pytoui/mips32el--musl--stable-2025.08-1/bin/mipsel-buildroot-linux-musl-gcc"
ar = "/home/murphy/pyproj/pytoui/mips32el--musl--stable-2025.08-1/bin/mipsel-buildroot-linux-musl-ar"

rustflags = [
    "-C", "link-arg=-lm",
    "-C", "link-arg=-lc",
]

[unstable]
build-std = ["std", "panic_abort"]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-lm",
    "-C", "link-arg=-lc",
]
